# logfilename                                              [owner:group]  mode  count  size  when  flags
__HOME__/services/osc-runner/osc-runner.log                               640   5      1024  *     NJ
